#!/usr/bin/env bash
#
# Copyright (C) 2025 Luna
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

cat >> ${SYSTEM_DIR}/etc/permissions/privapp-permissions-de.dylt.yanndroid.screenresolution.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/resolutionAppPermissionsXMLGen.sh -->
<privapp-permissions xmlns:android="http://schemas.android.com/apk/res/android">
    <permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
    
    <package android:name="de.dylt.yanndroid.screenresolution">
        <permission android:name="android.permission.WRITE_SECURE_SETTINGS" />
    </package>
</privapp-permissions>
<!-- autogenerated by ./src/misc/scripts/rom_modifier_scripts/resolutionAppPermissionsXMLGen.sh -->
EOF

# give perms:
chmod 644 "${SYSTEM_DIR}/etc/permissions/privapp-permissions-de.dylt.yanndroid.screenresolution.xml"
chown root:root "${SYSTEM_DIR}/etc/permissions/privapp-permissions-de.dylt.yanndroid.screenresolution.xml"
chcon u:object_r:system_file:s0 "${SYSTEM_DIR}/etc/permissions/privapp-permissions-de.dylt.yanndroid.screenresolution.xml"